version: '3.3'
services:
  rst-workbench-frontend:
    labels:
      name: rst-workbench-frontend
      type: frontend
    build:
      context: .
      args:
      - DOMAIN
      dockerfile: Dockerfile-frontend-server
    environment:
      - DOMAIN
    restart: unless-stopped
    volumes:
      - ./nginx-certbot/data/nginx:/etc/nginx/conf.d
      - ./nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ./nginx-certbot/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'chown -R nginx:root /etc/letsencrypt && echo DOMAIN: $DOMAIN && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ./nginx-certbot/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  hilda-service:
    labels:
      name: hilda
      format: hilda
      type: rst-parser
    image: hilda-service:2018-10-18
    ports:
    - 9102:8000
